/*!
 * ScrollToPlugin 3.2.4
 * https://greensock.com
 *
 * @license Copyright 2008-2020, GreenSock. All rights reserved.
 * Subject to the terms at https://greensock.com/standard-license or for
 * Club GreenSock members, the agreement issued with that membership.
 * @author: Jack Doyle, jack@greensock.com
*/
let gsap,_coreInitted,_window,_docEl,_body,_toArray,_config,_windowExists=()=>"undefined"!=typeof window,_getGSAP=()=>gsap||_windowExists()&&(gsap=window.gsap)&&gsap.registerPlugin&&gsap,_isString=t=>"string"==typeof t,_max=(t,o)=>{let e="x"===o?"Width":"Height",l="scroll"+e,i="client"+e;return t===_window||t===_docEl||t===_body?Math.max(_docEl[l],_body[l])-(_window["inner"+e]||_docEl[i]||_body[i]):t[l]-t["offset"+e]},_buildGetter=(t,o)=>{let e="scroll"+("x"===o?"Left":"Top");return t===_window&&(null!=t.pageXOffset?e="page"+o.toUpperCase()+"Offset":t=null!=_docEl[e]?_docEl:_body),()=>t[e]},_getOffset=(t,o)=>{let e=_toArray(t)[0].getBoundingClientRect(),l=!o||o===_window||o===_body,i=l?{top:_docEl.clientTop-(_window.pageYOffset||_docEl.scrollTop||_body.scrollTop||0),left:_docEl.clientLeft-(_window.pageXOffset||_docEl.scrollLeft||_body.scrollLeft||0)}:o.getBoundingClientRect(),s={x:e.left-i.left,y:e.top-i.top};return!l&&o&&(s.x+=_buildGetter(o,"x")(),s.y+=_buildGetter(o,"y")()),s},_parseVal=(t,o,e,l)=>isNaN(t)||"object"==typeof t?_isString(t)&&"="===t.charAt(1)?parseFloat(t.substr(2))*("-"===t.charAt(0)?-1:1)+l:"max"===t?_max(o,e):Math.min(_max(o,e),_getOffset(t,o)[e]):parseFloat(t),_initCore=()=>{gsap=_getGSAP(),_windowExists()&&gsap&&document.body&&(_window=window,_body=document.body,_docEl=document.documentElement,_toArray=gsap.utils.toArray,gsap.config({autoKillThreshold:7}),_config=gsap.config(),_coreInitted=1)};export const ScrollToPlugin={version:"3.2.4",name:"scrollTo",rawVars:1,register(t){gsap=t,_initCore()},init(t,o,e,l,i){_coreInitted||_initCore();let s=this;s.isWin=t===_window,s.target=t,s.tween=e,"object"!=typeof o?_isString((o={y:o}).y)&&"max"!==o.y&&"="!==o.y.charAt(1)&&(o.x=o.y):o.nodeType&&(o={y:o,x:o}),s.vars=o,s.autoKill=!!o.autoKill,s.getX=_buildGetter(t,"x"),s.getY=_buildGetter(t,"y"),s.x=s.xPrev=s.getX(),s.y=s.yPrev=s.getY(),null!=o.x?(s.add(s,"x",s.x,_parseVal(o.x,t,"x",s.x)-(o.offsetX||0),l,i,Math.round),s._props.push("scrollTo_x")):s.skipX=1,null!=o.y?(s.add(s,"y",s.y,_parseVal(o.y,t,"y",s.y)-(o.offsetY||0),l,i,Math.round),s._props.push("scrollTo_y")):s.skipY=1},render(t,o){let e,l,i,s,r,n=o._pt,{target:_,tween:a,autoKill:d,xPrev:p,yPrev:g,isWin:c}=o;for(;n;)n.r(t,n.d),n=n._next;e=c||!o.skipX?o.getX():p,i=(l=c||!o.skipY?o.getY():g)-g,s=e-p,r=_config.autoKillThreshold,o.x<0&&(o.x=0),o.y<0&&(o.y=0),d&&(!o.skipX&&(s>r||s<-r)&&e<_max(_,"x")&&(o.skipX=1),!o.skipY&&(i>r||i<-r)&&l<_max(_,"y")&&(o.skipY=1),o.skipX&&o.skipY&&(a.kill(),o.vars.onAutoKill&&o.vars.onAutoKill.apply(a,o.vars.onAutoKillParams||[]))),c?_window.scrollTo(o.skipX?e:o.x,o.skipY?l:o.y):(o.skipY||(_.scrollTop=o.y),o.skipX||(_.scrollLeft=o.x)),o.xPrev=o.x,o.yPrev=o.y},kill(t){let o="scrollTo"===t;(o||"scrollTo_x"===t)&&(this.skipX=1),(o||"scrollTo_y"===t)&&(this.skipY=1)}};ScrollToPlugin.max=_max,ScrollToPlugin.getOffset=_getOffset,ScrollToPlugin.buildGetter=_buildGetter,_getGSAP()&&gsap.registerPlugin(ScrollToPlugin);export{ScrollToPlugin as default};